/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_HPP__
#define __APP_HPP__

#include "drivers_dht.hpp"

/*
 *  API_RELEASE is coming from the api yaml file version row
 *  'grep "  version:" api/thermostat_api.yaml | sed s/\ \ version:\ //'
 *  and is generated by the Makefile
 */

#ifndef API_RELEASE
#define API_RELEASE "Unavailable"
#endif

void app_init_before_wifi(void);
void app_init_after_wifi(void);
void app_deinit_on_wifi_disconnect(void);
char *app_info_json_stringify(char *dest = NULL, int len = 0);

extern char *app_name;
extern char *app_release;

#endif