/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_EVENT_CODES_H__
#define __APP_EVENT_CODES_H__

#define REMOTELOG_RESTORE_CFG_ERROR 0x1000
#define REMOTELOG_CFG_STRINGIFY_HEAP_EXHAUSTED 0x1001
#define REMOTELOG_INIT_DEFAULT_CFG 0x1002
#define REMOTELOG_CHECK_ANSWER_UNEXPECTED_HOST_ANSWER 0x1003
#define REMOTELOG_SERVER_DIDNT_ANSWER 0x1004
#define REMOTELOG_POST_INFO_HEAP_EXHAUSTED 0x1005
#define REMOTELOG_SERVER_NOT_AVAILABLE 0x1006
#define REMOTELOG_SERVER_AVAILABLE 0x1007
#define REMOTELOG_OVERWRITING_UNREPORTED_EVENTS 0x1008
#define REMOTELOG_NO_MORE_OVERWRITING_UNREPORTED_EVENTS 0x1009

#define CTRL_SETTINGS_RESTORE_CFG_ERROR 0x1010
#define CTRL_SETTINGS_STRINGIFY_HEAP_EXHAUSTED 0x1011
#define CTRL_SETTINGS_FULL_JSON_STRINGIFY_HEAP_EXHAUSTED 0x1012
#define CTRL_VARS_STRINGIFY_HEAP_EXHAUSTED 0x1013
#define CTRL_ADV_SETTINGS_RESTORE_CFG_ERROR 0x1014
#define CTRL_ADV_SETTINGS_CFG_STRINGIFY_HEAP_EXHAUSTED 0x1015
#define CTRL_UPDATE_SETPOINT_NO_PROGRAM_AVAILABLE 0x1027
#define CTRL_INIT_DEFAULT_CTRL_CFG 0x1016
#define CTRL_INIT_DEFAULT_ADV_CTRL_CFG 0x1017
#define CTRL_INIT_CUSTOM_ADV_CTRL_CFG 0x1018

#define CTRL_PRG_NOT_FOUND 0x1020
#define CTRL_PRG_LIST_RESTORE_ERROR 0x1021
#define CTRL_PRG_LIST_RESTORE_HEAP_EXHAUSTED 0x1022
#define CTRL_PRG_LIST_STRINGIFY_HEAP_EXHAUSTED 0x1023
#define CTRL_PRG_LOAD_NO_PROGRAM_LIST 0x1024
#define CTRL_PRG_LOAD_NO_PROGRAM_ID 0x1025
#define CTRL_PRG_LOAD_BAD_SYNTAX 0x1026
#define CTRL_PRG_LOAD_HEAP_EXHAUSTED 0x1027
#define CTRL_PRG_INIT_DEFAULT_PRGM_LIST 0x1028
#define CTRL_PRG_STRINGIFY_HEAP_EXHAUSTED 0x1029
#define CTRL_PRG_ADD_HEAP_EXHAUSTED 0x102A

#define TEMPLOG_INIT_HEAP_EXHAUSTED 0x1030
#define TEMPLOG_RESTORE_CFG_ERROR 0x1031
#define TEMPLOG_CFG_STRINGIFY_HEAP_EXHAUSTED 0x1032
#define TEMPLOG_CUSTOM_CAL_CFG 0x1033
#define TEMPLOG_DEFAULT_CAL_CFG 0x1034

#define APP_INFO_STRINGIFY_HEAP_EXHAUSTED 0x1040

#define APP_ROUTES_SETCTRLSETTINGS_HEAP_EXHAUSTED 0x1050
#define APP_ROUTES_CREATEPROGRAM_HEAP_EXHAUSTED 0x1051
#define APP_ROUTES_UPDATEPROGRAM_HEAP_EXHAUSTED 0x1052
#define APP_ROUTES_GETCTRLEVENTS_HEAP_EXHAUSTED 0x1053
#define APP_ROUTES_GETCTRLEVENTS_NEXT_HEAP_EXHAUSTED 0x1054
#define APP_ROUTES_GETCTRLEVENTS_NEXT_PENDING_RES_QUEUE_FULL 0x1055
#define APP_ROUTES_GETCTRLEVENTS_FIRST_HEAP_EXHAUSTED 0x1056
#define APP_ROUTES_GETCTRLEVENTS_FIRST_PENDING_RES_QUEUE_FULL 0x1057

#endif
