/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_EVENT_CODES_H__
#define __APP_EVENT_CODES_H__

#define REMOTELOG_RESTORE_CFG_FS_NOT_AVAILABLE 0x01A0
#define REMOTELOG_RESTORE_CFG_INCOMPLETE 0x01A1
#define REMOTELOG_SAVED_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x01A2
#define REMOTELOG_SAVED_CFG_NOT_UPDATED_INCOMPLETE 0x01A3
#define REMOTELOG_REMOVE_CFG_FS_NOT_AVAILABLE 0x01A4
#define REMOTELOG_SAVE_CFG_FS_NOT_AVAILABLE 0x01A5
#define REMOTELOG_SAVE_CFG_CANNOT_OPEN_FILE 0x01A6
#define REMOTELOG_SAVE_CFG_HEAP_EXHAUSTED 0x01A7
#define APP_REMOTELOG_INIT_DEFAULT_CFG 0x01A8

#define TEMP_CTRL_RESTORE_CFG_FS_NOT_AVAILABLE 0x01B0
#define TEMP_CTRL_RESTORE_CFG_INCOMPLETE 0x01B1
#define TEMP_CTRL_SAVED_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x01B2
#define TEMP_CTRL_SAVED_CFG_NOT_UPDATED_INCOMPLETE 0x01B3
#define TEMP_CTRL_REMOVE_CFG_FS_NOT_AVAILABLE 0x01B4
#define TEMP_CTRL_SAVE_CFG_FS_NOT_AVAILABLE 0x01B5
#define TEMP_CTRL_SAVE_CFG_CANNOT_OPEN_FILE 0x01B6
#define TEMP_CTRL_RESTORE_ADV_CFG_FS_NOT_AVAILABLE 0x01B7
#define TEMP_CTRL_RESTORE_ADV_CFG_INCOMPLETE 0x01B8
#define TEMP_CTRL_SAVED_ADV_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x01B9
#define TEMP_CTRL_SAVED_ADV_CFG_NOT_UPDATED_INCOMPLETE 0x01BA
#define TEMP_CTRL_REMOVE_ADV_CFG_FS_NOT_AVAILABLE 0x01BB
#define TEMP_CTRL_SAVE_ADV_CFG_FS_NOT_AVAILABLE 0x01BC
#define TEMP_CTRL_SAVE_ADV_CFG_CANNOT_OPEN_FILE 0x01BD
#define TEMP_CTRL_INIT_DEFAULT_CTRL_CFG 0x01BE
#define TEMP_CTRL_INIT_DEFAULT_ADV_CTRL_CFG 0x01BF

#define TEMP_LOG_INIT_HEAP_EXHAUSTED 0x01C0

#define APP_GET_API_INFO_HEAP_EXHAUSTED 0x01D0
#define APP_GET_API_TEMP_CTRL_VARS_HEAP_EXHAUSTED 0x01D1
#define APP_GET_API_TEMP_CTRL_SETTINGS_HEAP_EXHAUSTED 0x01D2
#define APP_POST_API_TEMP_CTRL_SETTINGS_HEAP_EXHAUSTED 0x01D3
#define APP_GET_API_TEMP_CTRL_ADV_SETTINGS_HEAP_EXHAUSTED 0x01D4
#define APP_GET_API_REMOTELOG_SETTINGS_HEAP_EXHAUSTED 0x01D5
#define APP_POST_API_REMOTELOG_SETTINGS_HEAP_EXHAUSTED 0x01D6

#endif