/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_EVENT_CODES_H__
#define __APP_EVENT_CODES_H__

#define REMOTELOG_RESTORE_CFG_FS_NOT_AVAILABLE 0x0A00
#define REMOTELOG_RESTORE_CFG_INCOMPLETE 0x0A01
#define REMOTELOG_SAVED_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x0A02
#define REMOTELOG_SAVED_CFG_NOT_UPDATED_INCOMPLETE 0x0A03
#define REMOTELOG_REMOVE_CFG_FS_NOT_AVAILABLE 0x0A04
#define REMOTELOG_SAVE_CFG_FS_NOT_AVAILABLE 0x0A05
#define REMOTELOG_SAVE_CFG_CANNOT_OPEN_FILE 0x0A06
#define REMOTELOG_SAVE_CFG_HEAP_EXHAUSTED 0x0A07
#define REMOTELOG_INIT_DEFAULT_CFG 0x0A08
#define REMOTELOG_CHECK_ANSWER_UNEXPECTED_HOST_ANSWER 0x0A09
#define REMOTELOG_CHECK_ANSWER_UNEXPECTED_CLIENT_STATUS 0x0A0A
#define REMOTELOG_POST_INFO_HEAP_EXHAUSTED 0x0A0B
#define REMOTELOG_POST_INFO_UNEXPECTED_CLIENT_STATUS 0x0A0C

#define TEMP_CTRL_RESTORE_CFG_FS_NOT_AVAILABLE 0x0A10
#define TEMP_CTRL_RESTORE_CFG_INCOMPLETE 0x0A11
#define TEMP_CTRL_SAVED_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x0A12
#define TEMP_CTRL_SAVED_CFG_NOT_UPDATED_INCOMPLETE 0x0A13
#define TEMP_CTRL_REMOVE_CFG_FS_NOT_AVAILABLE 0x0A14
#define TEMP_CTRL_SAVE_CFG_FS_NOT_AVAILABLE 0x0A15
#define TEMP_CTRL_SAVE_CFG_CANNOT_OPEN_FILE 0x0A16
#define TEMP_CTRL_RESTORE_ADV_CFG_FS_NOT_AVAILABLE 0x0A17
#define TEMP_CTRL_RESTORE_ADV_CFG_INCOMPLETE 0x0A18
#define TEMP_CTRL_SAVED_ADV_CFG_NOT_UPDATED_FS_NOT_AVAILABLE 0x0A19
#define TEMP_CTRL_SAVED_ADV_CFG_NOT_UPDATED_INCOMPLETE 0x0A1A
#define TEMP_CTRL_REMOVE_ADV_CFG_FS_NOT_AVAILABLE 0x0A1B
#define TEMP_CTRL_SAVE_ADV_CFG_FS_NOT_AVAILABLE 0x0A1C
#define TEMP_CTRL_SAVE_ADV_CFG_CANNOT_OPEN_FILE 0x0A1D
#define TEMP_CTRL_INIT_DEFAULT_CTRL_CFG 0x0A1E
#define TEMP_CTRL_INIT_DEFAULT_ADV_CTRL_CFG 0x0A1F
#define TEMP_CTRL_INIT_CUSTOM_ADV_CTRL_CFG 0x0A20

#define TEMP_LOG_INIT_HEAP_EXHAUSTED 0x0A30

#define APP_GET_API_INFO_HEAP_EXHAUSTED 0x0A40
#define APP_GET_API_TEMP_CTRL_VARS_HEAP_EXHAUSTED 0x0A41
#define APP_GET_API_TEMP_CTRL_SETTINGS_HEAP_EXHAUSTED 0x0A42
#define APP_POST_API_TEMP_CTRL_SETTINGS_HEAP_EXHAUSTED 0x0A43
#define APP_GET_API_TEMP_CTRL_ADV_SETTINGS_HEAP_EXHAUSTED 0x0A44
#define APP_GET_API_REMOTELOG_SETTINGS_HEAP_EXHAUSTED 0x0A45
#define APP_POST_API_REMOTELOG_SETTINGS_HEAP_EXHAUSTED 0x0A46

#endif
